name: TFE template
description: "Custom TFE steps to plan and apply"

inputs:
  tfe_token:
    description: "Terraform token"
    required: true
  refname:
    description: "ref name"
    required: false
  tfe_workspace_name:
    description: "workspace name"
    required: true
  run_apply:
    description: "apply boolean"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo ${{ inputs.tfe_workspace_name}}
      shell: bash

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2

    - name: TFE Login
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_hostname: 'app.terraform.io'
        cli_config_credentials_token: ${{ inputs.tfe_token }}
        terraform_wrapper: false           

    - uses: ./.github/actions/iac_action
      name: IaC PreDeployment Setup
      with:
        set-vault-token-in-tfe: true
        enable-tf-validation: false    

    - name: TFE Init&Plan
      working-directory: ./
      run: |
        rm -rf *.tfstate
        terraform init
        terraform plan
      shell: bash

    - name: TFE Apply
      if: ${{ ( inputs.run_apply == 'yes' ) }}
      working-directory: ./
      run: |
        terraform apply -auto-approve
      shell: bash
        
    - name: remove .terraform directory
      run: |
        rm -rf  ~/.terraform.d
      shell: bash