name: plan
runs: 
  steps:    
  - uses: actions/checkout@v2

  - run: |
      echo ${{ env.TF_WORKSPACE_NAME}}
          
  - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2
