name: Matrix Merge Workflow
on:
  push:
    branches:
      - main
      - NPE

jobs:
  MatrixWorkFlow:
    name: WorkFlowPerEnvPerLocation
    runs-on: ubuntu-latest
    env:
      # SPN_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}  # No chnage needed
      # SPN_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }} # No chnage needed
      # SPN_TENANT_ID: ${{ secrets.SPN_TENANT_ID }} # No chnage needed
      # TFE_TOKEN: ${{ secrets.TFE_TOKEN }} # No chnage needed
      # GH_TOKEN: ${{ secrets.GH_TOKEN }} # No chnage needed
      # VAULT_ADDR: ${{ secrets.VAULT_ADDR }} # No chnage needed
      TF_WORKSPACE_NAME: "Azure-CloudPlatform-Cld3Shared-AKS-${{ matrix.environment }}-${{ matrix.location }}"   # No chnage needed
      # # Update for mongodb/default vault namespace in environment secret which is for the private and public keys or if any other service need vault access. default vault-token will be created in TFE workspace.
      # VAULT_NAMESPACE: ${{ secrets.VAULT_NAMESPACE }}
      # # Update the mongodb/default Role in environment secret which is required to access private and public keys in vault or if any other service need vault access. default vault-token will be created in TFE workspace. 
      # VAULT_ROLE: ${{ secrets.VAULT_ROLE }}

    strategy:
      matrix:
        # environment: ["NPE", "Prod"]
        # location: ["Eastus2", "Centralus"]
        include:
        - if: contains("NPE", github.ref) # special value
          environment: "NPE"                                         # regular value
          location: "Eastus2"

        - if: contains("NPE", github.ref) # special value
          environment: "NPE"                                         # regular value
          location: "Centralus"

        - if: contains("main", github.ref) # special value
          environment: "Prod"                                         # regular value
          location: "Eastus2"

        - if: contains("main", github.ref) # special value
          environment: "Prod"                                         # regular value
          location: "Centralus"
        
    steps:    
    - uses: actions/checkout@v2

    - run: |
        echo ${{ env.TF_WORKSPACE_NAME}}

    # - uses: actions/checkout@v2
    #   name: IaC Standard Workflow Action Checkout
    #   with:
    #     repository: Cloud-3-0-EMU/iac-standard-action
    #     token: ${{ secrets.GH_TOKEN }}
    #     path: .github/actions

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2

    # - name: TFE Login
    #   uses: hashicorp/setup-terraform@v1
    #   with:
    #     cli_config_credentials_hostname: 'automation.humana.com'
    #     cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
    #     terraform_wrapper: false           

    # - uses: ./.github/actions/iac_action
    #   name: IaC PreDeployment Setup
    #   with:
    #     set-vault-token-in-tfe: true    

    # - name: TFE Init&Plan
    #   working-directory: ./
    #   run: |
    #     rm -rf *.tfstate
    #     terraform init
    #     terraform plan

    # - name: TFE Apply
    #   working-directory: ./
    #   run: |
    #     terraform apply -auto-approve
    # - name: remove .terraform directory
    #   run: |
    #     rm -rf  ~/.terraform.d
