name: Matrix Merge Workflow
on:
  push:
    branches:
      - main
      - NPE

jobs:
  MatrixWorkFlowPlan:
    name: WorkFlowPerEnvPerLocation
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE_NAME: "Azure-CloudPlatform-Cld3Shared-AKS-${{ matrix.environment }}-${{ matrix.location }}"   # No chnage needed

    strategy:
      matrix:
        environment: ["NPE"]
        location: ["Eastus2", "Centralus"]
        
    steps:    
    - uses: actions/checkout@v2

    - run: |
        echo ${{ env.TF_WORKSPACE_NAME}}

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2

  MatrixWorkFlowApply:
    environment: NPE
    needs: MatrixWorkFlowPlan
    name: WorkFlowPerEnvPerLocation
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE_NAME: "Azure-CloudPlatform-Cld3Shared-AKS-${{ matrix.environment }}-${{ matrix.location }}"

    strategy:
      matrix:
        environment: ["NPE"]
        location: ["Eastus2", "Centralus"]
        
    steps:    
    - uses: actions/checkout@v2

    - run: |
        echo ${{ env.TF_WORKSPACE_NAME}}

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2

